package(default_visibility = ["//visibility:public"])

java_library(
  name = "oauth2",
  srcs = glob(['*.java']),
  deps = [
    "//third_party/google-oauth",
    "//third_party/jackson-core",
    "//third_party/logging:logging-api",
  ],
)
