package(default_visibility = ["//visibility:public"])

java_library(
  name = "io",
  srcs = glob(['*.java']),
  deps = [
    "//src/main/java/polyglot/protobuf",
    "//third_party/grpc",
    "//third_party/guava",
    "//third_party/logging:logging-api",
    "//third_party/protobuf",
  ],
)
