package(default_visibility = ["//visibility:public"])

java_library(
    name = "config",
    srcs = glob(["*.java"]),
    deps = [
        "//src/main/java/me/dinowernli/grpc/polyglot/protobuf",
        "//src/main/proto:config_proto",
        "//third_party/grpc",
        "//third_party/guava",
        "//third_party/jcommander",
        "//third_party/netty",
        "//third_party/protobuf",
    ],
)
