package(default_visibility = ["//src/main/java/polyglot:__pkg__"])

java_library(
  name = "command",
  srcs = glob(['*.java']),
  deps = [
   "//src/main/proto:config_proto",
   "//src/main/java/polyglot/grpc",
   "//src/main/java/polyglot/io",
   "//src/main/java/polyglot/oauth2",
   "//src/main/java/polyglot/protobuf",
   "//third_party/google-oauth",
   "//third_party/grpc",
   "//third_party/guava",
   "//third_party/logging:logging-api",
   "//third_party/protobuf",
  ],
)
