---
name: Bazel Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Bazel cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/bazel/_bazel_runner
            /private/var/tmp/_bazel_runner
          key: bazel-${{ matrix.os }}

      - name: Install Bazel
        uses: ./.github/actions/install

      - name: Run tests
        run: bazel test //src/...
